### ISSUE TITLE
Better classification of Function types

### ISSUE THREAD

**Issue by caiangums** [danilowoz/I-don-t-know-how-to-name-my-function#2]
### Description:
I noticed that the project classify **Types of Functions**  as:
- Functional
- Side-effect

As a "functional" function seems ambiguous, I suggest changing to:
- Pure
- Side-effect (or with Side-effects)

#### Details:
![image](https://user-images.githubusercontent.com/7551787/99679374-9f1f8b80-2a5a-11eb-9df8-c3c41c6c53e4.png)

![image](https://user-images.githubusercontent.com/7551787/99679652-f45b9d00-2a5a-11eb-93c0-d62b3620c236.png)

#### Dependencies: 
No dependencies

**Comment by danilowoz** [comment]
Thank you @caiangums, that makes sense. 

Would you mind open a PR changing it? If not, I'll take care of it later.
Here's the file: https://github.com/danilowoz/I-don-t-know-how-to-name-my-function/blob/master/src/components/options.ts

**Comment by caiangums** [comment]
Sure! I'll make it! 😄
